LOGGING_ENABLED = True
CAPITAL = 1_000_000  # example
MAX_RISK_PCT = 0.05

EOD_LOOKBACK_DAYS = 20

FUTURES_SPREAD_THRESHOLD = 0.0005  # 0.05%
OI_CHANGE_THRESHOLD = 0.02         # 2%
PRICE_RANGE_THRESHOLD = 0.015      # 1.5%

MARKET_STATES = [
    "ACCUMULATION",
    "RISK_TRANSFER",
    "EXPANSION",
    "NEUTRAL"
]
